# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, it is so important for Finance with Python. We will use it to generate data for our analysis.

             1. Numpy Arrays
             2. Numpy operation
             3. Numpy Indexing

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries like numpy) sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy

In [50]:
import numpy as np

## Numpy Arrays
Creating NumPy Arrays From a Python List We can create an array by directly converting a list:

In [53]:
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

In [54]:
np.array(my_list)

array([1, 2, 3, 4])

In [55]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [56]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built-in Methods

There are lots of built-in ways to generate Arrays

arange (Return evenly spaced values within a given interval)

In [57]:
list (range (0,5))

[0, 1, 2, 3, 4]

In [58]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [11]:
np.arange(0,11,2) # even no adding a step size

array([ 0,  2,  4,  6,  8, 10])

In [59]:
np.arange(1,11,2) #odd no

array([1, 3, 5, 7, 9])

In [13]:
#Generating Zeros and Ones:

In [60]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [61]:
type(1)

int

In [62]:
type(1.0)

float

In [63]:
np.zeros((5,3)) # pass a tupple

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [66]:
np.ones(2) # one function

array([1., 1.])

In [69]:
np.ones(1)*5

array([5.])

In [70]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### linspace (evenly spaced numbers over a specified interval):

In [21]:
# there is a difference between arrange & linspace

In [73]:
np.linspace(0,10,6) 

array([ 0.,  2.,  4.,  6.,  8., 10.])

### Random number

#### rand
Random values in a given shape from a uniform distribution over [0, 1)

In [74]:
np.random.rand(3)

array([0.03656757, 0.36216459, 0.10584705])

In [77]:
np.random.rand(3,5)

array([[0.47892518, 0.80709395, 0.7721688 , 0.85418415, 0.8492684 ],
       [0.23634364, 0.65265194, 0.58072375, 0.86039082, 0.1170706 ],
       [0.87229404, 0.09980357, 0.17774546, 0.15117249, 0.42207742]])

##### randn
Return a sample (or samples) from the "standard normal" distribution. Not Uniform.with mean 0 and variance with 1.


In [78]:
np.random.randn(3)

array([ 0.56856546,  0.04451366, -0.81088212])

In [80]:
np.random.randn(4,3)

array([[ 0.24329017,  1.50025808,  0.26444152],
       [-0.78361183, -1.01792348,  0.48249089],
       [-0.51503096, -1.13252667,  1.37949062],
       [ 1.99708689,  0.5012107 ,  0.70198057]])

##### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [85]:
np.random.randint(2,100)

62

In [86]:
np.random.randint(1,100,3)

array([41, 66, 81])

### Array Attributes and Methods


In [87]:
arr = np.arange(30)

In [88]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [99]:
ranarr = np.random.randint(1,10,8)

In [100]:
ranarr

array([9, 7, 6, 4, 6, 6, 1, 8])

In [43]:
#Reshape array

In [97]:
arr.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

#### max,min,argmax,argmin

In [101]:
ranarr

array([9, 7, 6, 4, 6, 6, 1, 8])

In [102]:
ranarr.max()

9

In [103]:
ranarr.argmax()

0

In [104]:
ranarr.min()

1

In [105]:
ranarr.argmin()

6