### NumPy part 3 (Indexing and Selection)

In this lecture we will discuss how to select elements or groups of elements from an array.

In [87]:
import numpy as np

In [88]:
arr = np.arange(0,11)

In [89]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Bracket indexing and Selection
(Same as python list)

In [91]:
arr[2] #Get a value at an index

2

In [92]:
arr[1:4] #Get values in a range / slice notation

array([1, 2, 3])

In [93]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [94]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

#### Broadcasting
(Numpy arrays differ from a normal Python list because of their ability to broadcast)

In [95]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [97]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
#Slices
slice_of_arr = arr[0:5]

In [99]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [102]:
slice_of_arr[:]=100

In [103]:
slice_of_arr

array([100, 100, 100, 100, 100])

In [104]:
arr #Change in original arrey

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [105]:
arr_copy = arr.copy() #creat a copy

arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [106]:
arr_copy[:]=200

In [107]:
arr_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [108]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

#### Indexing a 2D array (matrices)

In [61]:
# mat = [row,col]
# mat = [row][col]

In [109]:
mat=np.array(([5,10,20],[20,25,30],[35,40,10]))
mat

array([[ 5, 10, 20],
       [20, 25, 30],
       [35, 40, 10]])

In [111]:
mat[1] #Indexing row

array([20, 25, 30])

In [112]:
mat[2]

array([35, 40, 10])

In [114]:
# Getting individual element value
mat[1][1]

25

In [115]:
mat[1,2] # use common notaion instaed of 2 brackets

30

In [116]:
#array slicing
mat

array([[ 5, 10, 20],
       [20, 25, 30],
       [35, 40, 10]])

In [117]:
#Shape top row
mat[0]

array([ 5, 10, 20])

In [118]:
#Shape (2,2) from top right corner
mat[:2,1:]

array([[10, 20],
       [25, 30]])

In [119]:
#Shape (2,2) from bottom left corner
mat[1:,:2]

array([[20, 25],
       [35, 40]])

In [122]:
#Shape bottom row
mat[2]

array([35, 40, 10])

In [121]:
#Shape bottom row
mat[2,:]

array([35, 40, 10])

#### Conditional Selection

In [123]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [124]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [125]:
bool_arr = arr>4

In [126]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [127]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [128]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [129]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

#### Thank you!